// File generated by importSupportedLocalesFromLocalazy.py, do not edit

package extension

val locales = setOf(
    "be",
    "bg",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "et",
    "fr",
    "hu",
    "in",
    "it",
    "ka",
    "pt",
    "ro",
    "ru",
    "sk",
    "sv",
    "uk",
    "zh-rCN",
    "zh-rTW",
)
