name: Danger CI

on: [pull_request, merge_group]

permissions: {}

jobs:
  check-secret:
    name: Check Enterprise Deploy Key
    runs-on: ubuntu-latest
    outputs:
      has_key: ${{ steps.check.outputs.has_key }}
    steps:
      - id: check
        run: echo "has_key=${{ secrets.ELEMENT_ENTERPRISE_DEPLOY_KEY != '' }}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    name: Danger main check
    needs: check-secret
    # Skip in forks, it doesn't work even with the fallback token
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'element-hq/element-x-android' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Add SSH private keys for submodule repositories
        if: ${{ needs.check-secret.outputs.has_key == 'true' }}
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.ELEMENT_ENTERPRISE_DEPLOY_KEY }}
      - name: Clone submodules
        if: ${{ needs.check-secret.outputs.has_key == 'true' }}
        run: git submodule update --init --recursive
      - run: |
          npm install --save-dev @babel/plugin-transform-flow-strip-types
      - name: Danger
        uses: danger/danger-js@58355dc2b274a87699c8b7deac01baba16d6f061 # 13.0.8
        with:
          args: "--dangerfile ./tools/danger/dangerfile.js"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          # Fallback for forks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
