name: Generate GitHub Pages
on:
  workflow_dispatch:
  schedule:
    # At 00:00 on every Tuesday UTC
    - cron: '0 0 * * 2'

jobs:
  generate-github-pages:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'element-hq/element-x-android'
    steps:
      - name: ⏬ Checkout with LFS
        uses: nschloe/action-cached-lfs-checkout@v1.2.2
      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Configure gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run World screenshots generation script
        run: |
          ./tools/test/generateWorldScreenshots.py
          mkdir -p screenshots/en
          cp tests/uitests/src/test/snapshots/images/* screenshots/en
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./screenshots
