name: "Validate Gradle Wrapper"
on:
  pull_request:
  merge_group:
  push:
    branches: [ main, develop ]

jobs:
  validation:
    name: "Validation"
    # Don't run in the merge queue again if the branch is up to date with `develop`
    if: github.event.merge_group.base_ref != 'refs/heads/develop'
    runs-on: ubuntu-latest
    # No concurrency required, this is a prerequisite to other actions and should run every time.
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
