name: Move new issues onto issue triage board v2

on:
  issues:
    types: [ opened ]

jobs:
  triage-new-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/vector-im/projects/91
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
