name: Validate Git LFS

on: [pull_request, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1.2.3

      - run: |
          ./tools/git/validate_lfs.sh
